apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: socks5-proxy-hpa
  namespace: proxy-socks5
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: socks5-proxy
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

